### PR TITLE
Milestone2

### PR DESCRIPTION
**Pull request by bafiam**
_**Navigate to readme to see a demo of how to navigate the site**_
#### What does this PR do?
1. Consist of the working code of the ror-social-scaffold project
 - Friendship model and associations
 - .User is able to send a friendship invitation
- .User is able to see a button “Invite to friendship” next to the name of user who is not my friend
- .User is able to see pending friendship invitations sent to me from other users.
- .User is able to accept or reject friendships invitation.
- .User is able to see the total count of friends they have
- .User is able to see the total count of pending friends requests
#### How should this be manually tested?
Clone the repo then navigate to the project directory,:
- .Follow the readme instructions for setup and running
- run `rspec` on terminal to run the test cases
### A simple Use Test:
ezgif-2-c3e356058188

### CODE REVIEW

**Review by Ispirett — CHANGES_REQUESTED** [review]
## Status changes required
Great job so far @bafiam @simoxsimo with this project you did a great! :+1:  :+1: 
There are just a few things missing see below.
- [x] I can't accept friend requests currently [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png)

- [x] Posts timeline includes posts written by logged-in user and their friends [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png). Curretly i can see the posts from people who are not friends with the user.

- [x]  User has to accept friendship request to start friendship  [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png)

**Comment by simoxsimo** [comment]
## Changes are done!!
As for the accept button, we don't have any issues with that button but when it is tested on smaller screens it creates that problem, so for now, try to accept friendship when you are at 'Timeline' page or use development tool to change resolution and then press the button since judging from the person who tested it on his screen it is working. Since we have a Full-HD screen we couldn't recreate that behavior even when using the development tool.

So we will try fixing it after deploying to Heroku since we can use tools like https://responsivedesignchecker.com/ to recreate that behavior on our screens and then fix it.

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello, 
Thank for the changes you did from the last reviews.
However, I still can't accept a friendship request. I clicked on the `Request Pending` button many times but nothing, no answer from the console and the database content didn't change.
```ruby
2.7.0 :001 > Friendship.all
  Friendship Load (0.6ms)  SELECT  "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 1, status: nil, created_at: "2020-04-03 03:35:18", updated_at: "2020-04-03 03:35:18", sender_id: 22, receiver_id: 21>, #<Friendship id: 2, status: nil, created_at: "2020-04-03 03:43:09", updated_at: "2020-04-03 03:43:09", sender_id: 21, receiver_id: 2>, #<Friendship id: 3, status: nil, created_at: "2020-04-03 03:45:05", updated_at: "2020-04-03 03:45:05", sender_id: 4, receiver_id: 21>]> 
2.7.0 :002 > 
```


Kindly fix that bug and submit a new code review request.
Thanks

Mael FOSSO

**Comment by simoxsimo** [comment]
Hello @maelfosso!
Request Pending isn't a clickable button, it means that the request is waiting for you to accept.
So to accept request press on notification on the navbar 'N' and then a drop-down will appear where you accept the friend request.
Then, the Request Pending button will turn into unfriend button where you can press to unfriend.

P.S. We did include a gif image that explains the execution in case you have a problem, you will find it at the start of the PR.

**Comment by maelfosso** [comment]
Hello @simoxsimo ,

Thank you for that.
I just sent and request to make it approved.

**Review by uche-inyama — APPROVED** [review]
## Approved.

Hi team :wave: 

This milestone is approved. Go on with the next milestone.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Pull request merged**
