### PR TITLE
Milestone 6: Friendships v2

### PR DESCRIPTION
**Pull request by bafiam**
_**Navigate readme to see a demo of how to navigate the site**_
#### What does this PR do?
1. Consist of the working code of the ror-social-scaffold project
 - Our project implementation had already covered duplicate friend requests. When a user sends a friend request the "add friend button" changes to a pending notification that waits for 'accept' or 'reject' the friend request, so he cant send multiple requests to the same user.
- We also included a validation inside the Friendship model using both 'sender_id' and 'receiver_id' as a compound validation.
#### How should this be manually tested?
Clone the repo then navigate to the project directory:

- .Follow the readme instructions for setup and running
- run `rspec` on the terminal to run the test cases

### A simple test case:
ezgif-2-c3e356058188

### CODE REVIEW

**Review by mosaaleb — CHANGES_REQUESTED** [review]
### Amazing job @simoxsimo @bafiam :clap:

That's great pull request description, Tests are green. Yet, there still some work to do before moving on:


- [x] There is a button to invite a user to friendship on users list page and on the single-user page -- You have already buttons on users show page, but we still need it in user's index page.



- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created -- Please take a look at the resources on pathwright to know more about this step.

- [x] =>
```ruby
def unfriend(other_user)
  receivers.delete(other_user)
end
```

The `unfriend` method in User class, will remove friend of the current user, only if the current user is the one who sent the request -- we need to handle the case if the current user is the one who received the request.

You can add `senders.delete(other_user)` to fix this issue.

Also, note that you need to handle the duplicated friendship record with a reversed user-friend when you add this requirement.


- [x] There should be NO application logic in the views nor helpers.
In `_post.html.erb`, you have this snippet:
```ruby
<% if my_friends_post(post.user_id) || post.user_id == current_user.id %>
```

for checking if the post belongs to the current user friends or not, which is not the right way to handle this case. You can move this logic in the user model as `timeline_posts` methods which will grab all the posts of the current user and his friends, then consume this method in posts_controller to make it available in the views.

Remember that everything connected with data processing should be encapsulated in models and used in controllers.

- [x] There are not enough tests. The user model doesn't have any unit tests. The friendship model has some methods that are not yet tested.



Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

**Comment by bafiam** [comment]
All changes implemented.
_**NB: The rubocop error is related to their latest update not a code issue, we have double checked the file in accordance to the microverse lint files.**_ 
Thank you.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job! @bafiam 
You've handled suggested changes really well! However, you have some errors as displayed by stickler and you need to attend to these before you can get an approval. Please make the appropriate fixes and request another review! I wish you the very best and see you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by bolah2009 — APPROVED** [review]
Nice job implementing the suggested changes from previous TSEs, It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good luck with your next milestone. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Pull request merged**
